---
# Headless Service because the clusterIP is set to “None.”
apiVersion: v1
kind: Service
metadata:
  name: mongo
  namespace: {{ .Values.namespace }}
  labels:
    name: mongo
spec:
  ports:
    - port: {{ .Values.deployment.mongodb.port }}
      targetPort: {{ .Values.deployment.mongodb.port }}
  clusterIP: None
  selector:
    role: mongo
