apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
  namespace: {{ .Values.namespace }}
type: kubernetes.io/basic-auth
stringData:
  username: {{ .Values.secrets.username }}
  password: {{ .Values.secrets.password }}
  database: {{ .Values.secrets.database }}
